# SwiftHub Cloud Infrastructure
#
# This directory contains Terraform configurations for deploying SwiftHub
# to Google Cloud Platform (GCP).
#
# WARNING: This is a reference implementation. Do not apply without:
# 1. Reviewing costs with `terraform plan`
# 2. Updating variables.tf with your project ID
# 3. Setting up GCP authentication (gcloud auth application-default login)
#
# Usage:
#   terraform init
#   terraform plan -var="project_id=your-project-id"
#   terraform apply -var="project_id=your-project-id"

provider "google" {
  project = var.project_id
  region  = var.region
}

# 1. Medallion Storage Layer (GCS Buckets)
resource "google_storage_bucket" "medallion_buckets" {
  for_each      = var.bucket_names
  name          = "${each.value}-${var.environment}"
  location      = var.region
  force_destroy = true

  uniform_bucket_level_access = true

  lifecycle_rule {
    condition {
      age = 90
    }
    action {
      type = "Delete"
    }
  }

  labels = {
    environment = var.environment
    project     = "swifthub"
  }
}

# 2. BigQuery Analytics Warehouse (Analytical Serving)
resource "google_bigquery_dataset" "swifthub_warehouse" {
  dataset_id                  = "swifthub_warehouse_${var.environment}"
  friendly_name               = "SwiftHub Data Warehouse"
  description = "Star schema models generated by dbt transformations"
  location                    = "ASIA-SOUTHEAST2" # Jakarta
  default_table_expiration_ms = 3600000 * 24 * 30 # 30 days

  labels = {
    environment = var.environment
    project     = "swifthub"
  }
}

# 3. Cloud Run Service for FastAPI Operational API
resource "google_cloud_run_v2_service" "api_serving" {
  name     = "swifthub-serving-api"
  location = var.region
  ingress  = "INGRESS_TRAFFIC_ALL"

  template {
    containers {
      image = "gcr.io/${var.project_id}/swifthub-api:latest"
      
      ports {
        container_port = 8000
      }

      resources {
        limits = {
          cpu    = "1.0"
          memory = "512Mi"
        }
      }

      env {
        name  = "ENVIRONMENT"
        value = var.environment
      }
      env {
        name  = "BIGQUERY_DATASET"
        value = google_bigquery_dataset.swifthub_warehouse.dataset_id
      }
    }
  }

  traffic {
    type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    percent = 100
  }
}

# 4. IAM Access Policy to allow unauthenticated API requests (Public Serving)
resource "google_cloud_run_v2_service_iam_member" "public_access" {
  name     = google_cloud_run_v2_service.api_serving.name
  location = google_cloud_run_v2_service.api_serving.location
  role     = "roles/run.viewer"
  member   = "allUsers"
}

# 5. Cloud Build Trigger for CI/CD
resource "google_cloudbuild_trigger" "main" {
  name = "swifthub-ci-trigger"
  location = var.region
  
  github {
    owner = var.github_owner
    name  = var.github_repo
    
    push {
      branch = "^main$"
    }
  }
  
  filename = "cloudbuild.yaml"
}

# 6. Monitoring Dashboard
resource "google_monitoring_dashboard" "swifthub_dashboard" {
  dashboard_json = jsonencode({
    displayName = "SwiftHub Platform Dashboard"
    grids = [
      {
        tiles = [
          {
            title = "API Latency (p99)"
            widget = {
              heatmap = {
                timeseries = [
                  {
                    target_series = {
                      time_series_query_language = {
                        query = "fetch cloud_run_revision\n| metric 'run.googleapis.com/latency'\n| filter resource.project_id = '${var.project_id}'\n| group_by [1m], [value.latency_mean: avg(value.latency_mean)]\n| every 1m"
                      }
                    }
                    target_display_format = "API Latency"
                  }
                ]
              }
            }
          }
        ]
      }
    ]
  })
}

# Outputs
output "gcs_bucket_urls" {
  description = "GCS bucket URLs for the medallion layers"
  value = {
    for key, bucket in google_storage_bucket.medallion_buckets :
    key => bucket.url
  }
}

output "bigquery_dataset_id" {
  description = "BigQuery dataset ID"
  value = google_bigquery_dataset.swifthub_warehouse.dataset_id
}

output "api_service_url" {
  description = "Cloud Run API service URL"
  value = google_cloud_run_v2_service.api_serving.uri
}
